# Generated by Django 3.2.13 on 2022-04-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=128, verbose_name='id события в календаре')),
                ('date_start', models.DateTimeField(verbose_name='Время начала события')),
                ('date_end', models.DateTimeField(verbose_name='Время окончания события')),
                ('error', models.BooleanField(default=False, verbose_name='Пересекается с другими событиями компании?')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='hall.hall', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('date_start',),
            },
        ),
    ]
