# Generated by Django 3.2.13 on 2022-04-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='error',
        ),
    ]
