# Generated by Django 3.2.13 on 2022-04-17 09:23

from django.db import migrations
from django_celery_beat.models import PeriodicTask, IntervalSchedule


def add_task(apps, schema_editor):
    PeriodicTask.objects.create(
        name='Import events',
        task='event.tasks.import_events',
        interval=IntervalSchedule.objects.get_or_create(
            every=2,
            period='minutes',
        )[0],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_error'),
    ]

    operations = [
        migrations.RunPython(
            add_task,
            reverse_code=migrations.RunPython.noop
        ),
    ]
