version:  "3.8"
services:
  backend:
    build:
      context: .
    volumes:
      - ./backend:/appevent/backend/
      - ./logs:/appevent/logs
    image: backend:django
    container_name: django_container
    command: sh -c "
      python manage.py collectstatic --noinput --clear -v 1 &&
      python manage.py migrate &&
      gunicorn main.wsgi --bind 0.0.0.0:8000"
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'appeventdb'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
     - ./data/mysql/db:/var/lib/mysql
    container_name: mysql


  redis:
    image: redis
    container_name: redis

  celery:
    restart: always
    build:
      context: .
    command: celery -A main worker -l INFO
    volumes:
      - ./backend:/appevent/backend
      - ./logs:/appevent/logs
    container_name: celery
    depends_on:
      - backend
      - redis
    env_file:
      - .env

  beat:
    restart: always
    build:
      context: .
    command: celery -A main beat -l INFO
    volumes:
      - ./backend:/appevent/backend
      - ./logs:/appevent/logs
    container_name: beat
    depends_on:
      - backend
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/main/static:/static
      - ./backend/main/media:/media
    depends_on:
      - backend
    container_name: nginx
