# Generated by Django 3.2.13 on 2022-04-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название зала')),
                ('google_calendar_id', models.CharField(max_length=255, verbose_name='id календаря google')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall', to='company.company', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ('name',),
            },
        ),
    ]
