# Generated by Django 3.2.13 on 2022-04-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_alter_hall_google_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='id календаря google'),
        ),
    ]
